# Generated by Django 3.2.5 on 2021-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='room_no',
        ),
    ]
