# Generated by Django 3.2.4 on 2021-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_chats_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
    ]
